### ISSUE TITLE
About the test（MBATA_GAN）?

### ISSUE THREAD

**Issue by Hcshenziyang** [sstary/SSRS#1]
Thank you for your work. From the test code, I found that the test phase also required the source domain image. In general, the test phase only needs the target domain image to get the result. I am not sure if images in the source domain are necessary during the testing phase? Or can the model directly extract the weight of the backbone network for testing?

**Comment by sstary** [comment]
Sorry for not replying in time. As you understand, in the current model, the test phase also requires source domain images. If the input from the source domain is removed, the target domain image cannot be aligned through the MBA module, which we believe will affect the result. If you're interested, maybe you can do a simple test. We would be happy to receive your further feedback.

**Comment by sstary** [comment]
> Sorry for not replying in time. As you understand, in the current model, the test phase also requires source domain images. If the input from the source domain is removed, the target domain image cannot be aligned through the MBA module, which we believe will affect the result. If you're interested, maybe you can do a simple test. We would be happy to receive your further feedback.

Sorry for not replying in time. As you understand, in the current model, the test phase also requires source domain images. If the input from the source domain is removed, the target domain image cannot be aligned through the MBA module, which we believe will affect the result. If you're interested, maybe you can do a simple test. We would be happy to receive your further feedback.
