### ISSUE TITLE
模型问题

### ISSUE THREAD

**Issue by ccstrong007** [sstary/SSRS#10]
你好，这个只是开源了在文章中的进行对比的模型代码，但是文章所用的模型RS3Mamba是不是不进行开源啊。

**Comment by sstary** [comment]
你好，本仓库包含了我个人所有的工作，RS3Mamba代码会在近期上传。

**Comment by ccstrong007** [comment]
好的谢谢您 您的分享很有用感谢

**Comment by sstary** [comment]
你好，模型已经上传，如果对你有用，请给一个star。
