### ISSUE TITLE
can author share the requirements?

### ISSUE THREAD

**Issue by yizhixiaochenzi** [sstary/SSRS#11]
i dont look for the requirements

**Comment by sstary** [comment]
For RS3Mamba？

**Comment by sstary** [comment]
For RS3Mamba, 请根据https://github.com/JCruan519/VM-UNet?tab=readme-ov-file安装主要的vss相关的包。

RS3Mamba以及本仓库其他任何方法，它们都不对特定的Pytorch版本有依赖，一般的环境都可以良好工作。
