### ISSUE TITLE
R50+ViT-B_16.npz

### ISSUE THREAD

**Issue by JAYCHUS** [sstary/SSRS#13]
请问有这个预训练权重文件吗 或者给个地址 vit主页翻了一会了找不到 😥非非非非常感谢您
R50+ViT-B_16.npz

**Comment by sstary** [comment]
你好，不客气。该权重在：https://console.cloud.google.com/storage/browser/vit_models;tab=objects?prefix=&forceOnObjectsSortingFiltering=false 中的imagenet21k 目录可找到。

**Comment by sstary** [comment]
该权重我们是从TransUNet的仓库找过去的，并非Vit。
