### ISSUE TITLE
RS^3Mamba：dataloader

### ISSUE THREAD

**Issue by 1064028322** [sstary/SSRS#16]
utils_Mamba.py文件中204行报错
```
201        # Data augmentation
202        # data_p, boundary_p, label_p = self.data_augmentation(data_p, boundary_p, label_p)
203        data_p, label_p = self.data_augmentation(data_p, label_p)
204        object_p = object_process(object_p)
```
我看这个 object_p没有用到并把它注释，又报如下错误
`  File "train_Mamba.py", line 154, in <module>
    train(net, optimizer, 50, scheduler)
  File "train_Mamba.py", line 116, in train
    for batch_idx, (data, boundary, object, target) in enumerate(train_loader):
ValueError: not enough values to unpack (expected 4, got 2)
`
感觉是dataloader的问题，请问大佬这个怎么解决

**Comment by sstary** [comment]
你好，这里的object在本项目中没用，我们更新了以下代码：for batch_idx, (data, target) in enumerate(train_loader)  in train_Mamba.py。
