### ISSUE TITLE
数据集eroded laba：关于ERODED_FOLDER路径的设置问题

### ISSUE THREAD

**Issue by WangTianYi0102** [sstary/SSRS#18]
你好！，我想问一下ERODED_FOLDER里面应该存放哪些内容，是存放切割之前的数据集吗？
![1713362128573](https://github.com/sstary/SSRS/assets/163794144/0193afa6-38e1-431c-a059-b4dbbf0dec3b)

**Comment by sstary** [comment]
你好，在vaihingen和potsdam的官方数据集中，都有一个所谓的“腐蚀”边界的数据集，在这个数据集中， 物体的边界是黑色的，不会进行准确率统计，因为这些数据集的边界本身存在小部分不准确的情况。你可以在下载的链接上看到带eroded是标签。
