### ISSUE TITLE
关于RSmamba的复现问题

### ISSUE THREAD

**Issue by NYB-AAA** [sstary/SSRS#20]
我在看到您上传RSmamba代码后尝试去复现，但是目前在vaihingen上多轮实验最高Miou也只是82.61，无法到达论文里的82.78，而且在miou达到82.61的那次实验里，大部分miou也是82.5左右，看起来跟论文里没有加入CCM模块的miou类似，超参数都与论文中一样，只调整了学习率调整器和测试的频率，而且测试频率也并不是越高越好，比如我有一次实验是将测试频率改为200iter测一次，结果还不如500测一次效果好，但是无论如何，目前实验无法达到论文精度，求解答，下面是我的一些实验结果：

这是学习率调整器默认25.35.45调整，500测试一次时的结果：
![image](https://github.com/sstary/SSRS/assets/130569364/ede3f64f-2ff7-4d87-b85a-2a1a6a076fe5)
这是学习率调整器默认25.35.45调整，200测试一次时的结果：
![image](https://github.com/sstary/SSRS/assets/130569364/a6f9baf3-2fb4-4ff3-adea-924507152894)
这是学习率调整器15.30调整，1000测试一次的结果：
![image](https://github.com/sstary/SSRS/assets/130569364/517c2bf1-74d1-44c0-b638-9e0efea62b03)
这是学习率调整器默认25.35.45调整，1000测试一次的结果：
![image](https://github.com/sstary/SSRS/assets/130569364/faea405c-8603-463f-a8b8-22392290f2b1)

**Comment by sstary** [comment]
你好，每次实验本身存在较大的波动，并不会稳定在一个固定值。你的baseline，即只有resnet分支的情况下跑出来多少呢？

增加测试频率本身并不会影响模型的优化过程，只是多测试会让好的模型得以记录而已。你需要和你的baseline，在你的环境中比较，论文中的值只代表我的实验环境，受随机挑选样本的影响，不同的模型环境能有接近的最优值，我认为就是一个能接受的结果了。

**Comment by NYB-AAA** [comment]
这是只有resnet分支时，学习率25.35.45调整，隔1000测一次的结果：
![image](https://github.com/sstary/SSRS/assets/130569364/6eae6e4a-6f35-495d-a214-df3c84fd7c54)
和上面同样的参数设置下对比，只有resnet分支时的miou更高，rsmamba同样的参数设置下隔500测一次才能找到比只有resnet分支高的结果，这个结果波动会这么大吗，能波动到百分之1吗，我总感觉这个结果有点不合理，我觉得rsmamba再波动，也总会比只有resnet分支的结果高吧，但是实验结果不是这样

**Comment by sstary** [comment]
我的baseline也差不多是这样的结果，最佳miou在82+-0.1左右，你可以跑几组单resnet分支的实验，这个数据集本身的波动就很大，因为模型存在很多随机因素，包含decoder的权值，训练样本采集顺序等。

**Comment by NYB-AAA** [comment]
感谢解答，我多进行几次实验吧，再换lovada数据集试一下，请问对loveda的数据集处理需要先将每张图裁剪之后再拼接吗，还是直接输入给模型大图进行训练

**Comment by sstary** [comment]
LoveDA数据集的大小为1024*1024，我们直接将原大小输入到SAM中进行的预处理。你也可以自行对比不同输入尺寸的效果，自行选择。

**Comment by NYB-AAA** [comment]
> LoveDA数据集的大小为1024*1024，我们直接将原大小输入到SAM中进行的预处理。你也可以自行对比不同输入尺寸的效果，自行选择。语义分割模型训练时我们都采用的256输入，主要考虑到显存等因素。

感谢解答
