### ISSUE TITLE
预训练权重

### ISSUE THREAD

**Issue by LPZliu** [sstary/SSRS#21]
你好 你可以给我resnet50-VIT的 预权重吗

**Comment by sstary** [comment]
you can get the pre-trained model here: https://github.com/Beckschen/TransUNet?tab=readme-ov-file

**Comment by LPZliu** [comment]
非常感谢您



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月06日 18:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sstary/SSRS] 预训练权重 (Issue #21) |

you can get the pre-trained model here: https://github.com/Beckschen/TransUNet?tab=readme-ov-file
