### ISSUE TITLE
FD-GLGAN: code of FD-GLGAN

### ISSUE THREAD

**Issue by EvaEVL** [sstary/SSRS#22]
Hi! I started to disassemble the article repository (https://d197for5662m48.cloudfront.net/documents/publicationstatus/171167/preprint_pdf/79a9882af71506c082b12969e3fb439c.pdf). There are various algorithms in the repository, but I didn't see FD-GLGAN clearly. Can you tell me which of the algorithms in the repository should be used for FD-GLGAN?

**Comment by sstary** [comment]
Hello, because we just submitted it to TGRS, so we temporarily do not plan to upload the code of this work. We will update that as soon as we have a positive review.

**Comment by EvaEVL** [comment]
Got it, thanks for the answer
