### ISSUE TITLE
FTransUNet：测试过慢

### ISSUE THREAD

**Issue by YYDS-cc** [sstary/SSRS#27]
感谢大佬开源！

问题1：
训练过程中的验证阶段会特别慢，尤其是Potsdam数据集，
我在3090上测试6张图像需要接近一个小时的时间，请问这是正常的吗？有没有可以优化的地方呢？

问题2：
文中表格三中提到了UNETFormer，请问这个结果是根据现在的数据集划分跑出来的吗？
如果是的话，为什么我根据UNETFormer的官方代码跑出来的结果差了好多个点呢？

**Comment by sstary** [comment]
你好，
问题1：是的，测试极费时间，因此我们采用较小的Stride_Size=128进行训练阶段的测试，以此筛选出最好的模型，并仅对最终模型取Stride_Size=32进行测试，这样可以得到更好的结果。请将utils.py 中的Stride_Size改为128。

问题2：我们的结果是根据文中说明的数据集划分得到的。我们采用的是https://github.com/WangLibo1995/GeoSeg/tree/main/geoseg/models代码库中的代码，仅去掉了辅助分类头，实际代码为：https://github.com/sstary/SSRS/blob/main/SAM_RS/model/UNetFormer.py。你加载预训练模型了吗？你跑出来差多少呢？如果是1-2个百分点，可能是因为模型本身的训练波动。

**Comment by sstary** [comment]
如果对你有帮助，请点个star。
