### ISSUE TITLE
FTransUNet：About vfusenet

### ISSUE THREAD

**Issue by rssyhhu** [sstary/SSRS#28]
Hello, I want to train vfusenet according to the instructions of your project, but I can't see the model file about vfusenet. Can you tell me why? thank you

**Comment by sstary** [comment]
Hello, most of the comparison methods we used were open source. You can find the link in the paper of the corresponding method. The vfusenet link is: https://github.com/nshaud/DeepNetsForEO. This can also be seen in our Readme. You just need to go to the project and copy the model part.

**Comment by wsyhhu** [comment]
Thank you for your reply. My question is not clearly expressed. I have found the vfusenet project through your link. But I still can't find the vfusenet model file, only see about segnet. This may be my problem, but I still hope to get your help, thank you.

**Comment by sstary** [comment]
Yes, that's vfusenet which is a multimodal fusion network based on segnet. You can get more details in the paper 'Beyond RGB: Very high resolution urban remote sensing with multimodal deep networks'.

**Comment by wsyhhu** [comment]
OK, thanks for your help.

**Comment by sstary** [comment]
如果对你有帮助，请点个star。
