### ISSUE TITLE
Model Test：关于已保存的训练模型结果的复现

### ISSUE THREAD

**Issue by WangTianYi0102** [sstary/SSRS#29]
您好！我在对于我之前在训练过程中保存的后缀为MIou值的模型通过Test方式复现时，遇见了与原来的值不匹配的情况，比如原本在82.15的MIou值在复现时变成了0.061，请问这种情况该怎么办？

**Comment by sstary** [comment]
你好，能在训练阶段输出82.16说明测试阶段是没有问题的，本质上我们训练阶段调用的测试代码和单独测试的代码是完全一致的，均调用test函数。
可能的原因和办法：
1. 请检查是否成功加载模型，或者是否重复加载模型
2. 如果实在不行，可以直接调用Train模式，但是将训练阶段的test函数直接优先调用，通过这种方式也能直接进行测试。

**Comment by sstary** [comment]
如果对你有帮助，请点个star。
