### ISSUE TITLE
您好，我看代码部分缺少GLGAN的相关内容，可以麻烦您补充上吗？

### ISSUE THREAD

**Issue by SSSilvester** [sstary/SSRS#31]
您好，我看代码部分缺少GLGAN的相关内容，可以麻烦您补充上吗？

**Comment by sstary** [comment]
好的，感谢关注，我明天更新。

**Comment by sstary** [comment]
已经上传。如果对你有帮助，请给我一个star

**Comment by SSSilvester** [comment]
> 已经上传。如果对你有帮助，请给我一个star

非常感谢！我点好star啦！

**Comment by sstary** [comment]
上传的FTUNetformer加载预训练模型的代码有一些多余的内容，已经更新，请注意。

**Comment by SSSilvester** [comment]
> 上传的GLGAN/FTUNetFormer.py加载预训练模型的代码有一些多余的内容，已经更新，请注意。

收到！再次感谢您的帮助

**Comment by SSSilvester** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'pretrain/swinv2_base_patch4_window12to16_192to256_22kto1k_ft.pth'
您好，再次打扰您一下，我在尝试跑GLGAN的时候遇到了这个报错，我试图在https://github.com/microsoft/Swin-Transformer?tab=readme-ov-file下载相对应的预训练权重，但是不知道哪一个才是对应的window12to16,192to256以及22kto1k，可以再次麻烦您给我一个准确的下载链接吗？再次感谢您的帮助！

**Comment by sstary** [comment]
你好，感谢提醒，我已经更新了readme：
Please download the official pre-trained weights from ['Swin Transformer'](https://github.com/microsoft/Swin-Transformer)--'ImageNet-1K and ImageNet-22K Pretrained Swin-V2 Models'--['SwinV2-B*'](https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_base_patch4_window12to16_192to256_22kto1k_ft.pth) and ['SwinV2-L*'](https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_large_patch4_window12to16_192to256_22kto1k_ft.pth). The last cloumn '1K model' is what we used.

你可以按照指引看能否找到对应的权重文件。如果有问题再联系。

**Comment by sstary** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'pretrain/swinv2_base_patch4_window12to16_192to256_22kto1k_ft.pth' 您好，再次打扰您一下，我在尝试跑GLGAN的时候遇到了这个报错，我试图在https://github.com/microsoft/Swin-Transformer?tab=readme-ov-file 下载相对应的预训练权重，但是不知道哪一个才是对应的window12to16,192to256以及22kto1k，可以再次麻烦您给我一个准确的下载链接吗？再次感谢您的帮助！

你好，很抱歉，我发现SwinTransformerV2中的img_size不是正确值，应该是256，这样才能正确加载权重文件，不然会有几层对不上。
