### ISSUE TITLE
FTransUNet：请问可以用FTransUNet跑医学多模态分割？

### ISSUE THREAD

**Issue by ABFHJJGGGV** [sstary/SSRS#32]
非常好的工作！请问可以用FTransUNet这个模型跑3D医学多模态分割吗？

**Comment by sstary** [comment]
你好，我们的编码器部分不具有处理3d特征的能力，但是融合思路我觉得是通用的，或许你可以将其移植到一些3d数据处理的医疗模型上。

**Comment by ABFHJJGGGV** [comment]
好的 谢谢 祝科研顺利！
