### ISSUE TITLE
权重

### ISSUE THREAD

**Issue by 23del** [sstary/SSRS#33]
请问相应的权重文件有吗

**Comment by sstary** [comment]
请问你是指哪个方法？

**Comment by 23del** [comment]
GLGAN的，不行其他的都可以

**Comment by sstary** [comment]
你好，请参考问题31。

你好，感谢提醒，我已经更新了readme：
Please download the official pre-trained weights from ['Swin Transformer'](https://github.com/microsoft/Swin-Transformer)--'ImageNet-1K and ImageNet-22K Pretrained Swin-V2 Models'--['SwinV2-B*'](https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_base_patch4_window12to16_192to256_22kto1k_ft.pth) and ['SwinV2-L*'](https://github.com/SwinTransformer/storage/releases/download/v2.0.0/swinv2_large_patch4_window12to16_192to256_22kto1k_ft.pth). The last cloumn '1K model' is what we used.

你可以按照指引看能否找到对应的权重文件。如果有问题再联系。

**Comment by sstary** [comment]
你好，很抱歉，我发现SwinTransformerV2中的img_size不是正确值，应该是256，这样才能正确加载上述文件，不然会有几层对不上。

**Comment by 23del** [comment]
有权重的话，代码都可以直接测试嘛，我看有需要加载模型的？

**Comment by sstary** [comment]
你好，我们提供了编码器的预训练权重，暂时不会提供完整GLGAN和FD-GLGAN的训练权重，在有预训练权重的情况下，训练我们的模型并不会花费太多时间，而上传5组实验，两种方法一共10个模型比较占用网络存储空间。

**Comment by 23del** [comment]
作者你好，我想跑的图片大小是1024和model里的256不一致，没看到我们的配置文件，网络里的读取图片部分也是封装的，想问一下有简单的办法改一下吗（运行的FDGLGAN_LoveDA_R2U.py）

**Comment by sstary** [comment]
你好，需要改这几个地方:
1. swintransformerv2.py中img_size 改成1024,
2. 所有Window size 改成（1024,1024）
3. 数据加载器里注释掉这几行：
        # Get a random patch
        x1, x2, y1, y2 = get_random_pos(data_s, WINDOW_SIZE)
        data_s = data_s[:, x1:x2, y1:y2]
        label_s = label_s[x1:x2, y1:y2]

        x1, x2, y1, y2 = get_random_pos(data_t, WINDOW_SIZE)
        data_t = data_t[:, x1:x2, y1:y2]
        label_t = label_t[x1:x2, y1:y2]
4. 加载预训练模型的地方改成这样：
    if pretrained and weight_path is not None:
        # old_dict = torch.load(weight_path)['state_dict']
        old_dict = torch.load(weight_path)['model']
        model_dict = model.state_dict()
        old_dict = {'backbone.'+ k: v for k, v in old_dict.items() if ('backbone.' + k in model_dict)}
        model_dict.update(old_dict)
        ## if input is 1024 * 1024
        del model_dict['backbone.layers.0.blocks.1.attn_mask']
        del model_dict['backbone.layers.1.blocks.1.attn_mask']
        del model_dict['backbone.layers.3.blocks.0.attn.relative_position_index']
        del model_dict['backbone.layers.3.blocks.0.attn.relative_coords_table']
        del model_dict['backbone.layers.3.blocks.1.attn.relative_position_index']
        del model_dict['backbone.layers.3.blocks.1.attn.relative_coords_table']
        model.load_state_dict(model_dict, strict=False)
    return model
这样就没问题了，还有细节的话你在debug一下

**Comment by 23del** [comment]
/MultiHeadDotProductAttention_1/query/kernel is not a file in the archive

**Comment by 23del** [comment]
/MultiHeadDotProductAttention_1/query/kernel is not a file in the archive
这是FTransUNet的，他这个编译器的相关文件夹github没有，请问是怎么来的

**Comment by sstary** [comment]
你好，我们的代码应该不出出现这种调用。

**Comment by 23del** [comment]
谢谢，这个理论上也是可以跑loveda数据嘛，只是改一些名字？

**Comment by sstary** [comment]
是的，只需要修改数据集名字即可。

**Comment by 23del** [comment]
好的 感谢
