### ISSUE TITLE
RS^3Mamba: 请问 RS3Mamba 可以替换主干吗？

### ISSUE THREAD

**Issue by DevKPro** [sstary/SSRS#34]
你好作者，非常感谢您开源模型代码，请问 RS3Mamba 模型可以直接将 Resnet18 替换 Resnet50 等主干网络吗？我试了一下效果好像没太明显的提升，请问是我替换的方法不对吗？

**Comment by sstary** [comment]
你好，是可以替换的，但是确实不一定会有太大的影响，ResNet18和50有时候差别不大。
