### ISSUE TITLE
模型保存

### ISSUE THREAD

**Issue by weidaoquan** [sstary/SSRS#36]
你好，关于模型报错这块，名称没有后缀吗
torch.save(net.state_dict(), './resultsv_se_ablation/segnet256_epoch{}_{}'.format(e, acc))

**Comment by sstary** [comment]
你好，不用格式后缀也没关系，请问你报的什么错呢？

**Comment by weidaoquan** [comment]
你好，我想跑一下FTransUNet，可以直接输入三通道的遥感图像吗

**Comment by sstary** [comment]
我们的模型接收两种模态信息的输入，你可以根据你的输入调整模型的第一层，这不会有太大的影响。
