### ISSUE TITLE
FTransUNet：你好，想请问一下有关于DSM数据的问题？

### ISSUE THREAD

**Issue by EvilGhostY** [sstary/SSRS#39]
您好，您的工作对我启发很大，在实验过程中有一些疑问想向您请教。
1.我在做实验的过程中发现Potsdam的DSM数据不经过处理，灰度值是完全在0-255之间，但是vaihingen数据集的DSM的灰度值的最大值是超过255的，请问您在训练之前是否有对vaihingen数据集的DSM数据进行预处理（比如归一化处理使得灰度值在0-255之间）？同时可以看到每个DSM数据或多或少存在有异常点，是否需要对这些异常点进行与处理呢？
2.此外之前我利用vaihingen数据集的全部38张图像（而非论文里面所提的十几张数据）进行训练的测试之后，发现精度miou在82.0几，是否需要对一些参数例如训练次数等进行调整呢？
等待您的回复，谢谢！

**Comment by sstary** [comment]
你好，感谢你的关注。
1. 在我的所有工作中，我并未深入数据本身的噪音，我将所有输入视为标准数据，并且所有对比实验都在其基础上完成，这样也算是公平的。Potsdam和Vaihingen数据的处理流程都在until文件中，只有一个归一化，你可以查看对应代码。对于那些异常点，我们认为它可能会造成一些不好的影响，但是应该不大，深度模型期望有学习到这些噪音的能力。
2. 我认为你可以利用我们的方法，但是数据集就按照你的设置来，在不同设置的情况下，实验结果的miou是没有可对比性的，以你的实验结果为准即可，这是可以接受的。你只需要保证你所有的实验都在同样的实验环境在完成即可。
祝好，感谢。

**Comment by EvilGhostY** [comment]
感谢解答，谢谢 已经star了
