### ISSUE TITLE
MBATA_GAN：数据集

### ISSUE THREAD

**Issue by Xujingkk** [sstary/SSRS#40]
你好，请问ISPRS_dataset中返回10000个samples的依据是什么呀？

**Comment by sstary** [comment]
你好，我们的实验设置遵循了vFuseNet的设置，我的多个文章都保持这样的设定，请参考链接：https://github.com/nshaud/DeepNetsForEO/blob/master/SegNet_PyTorch_v2.ipynb。
另外，这个数字理论上应该基于总数据量除以batch size。比如Potsdam 共计16张6000*6000的大图，约等于9216张256*256的图，约等于一个epoch的数量。
