### ISSUE TITLE
FTransUNet: Environment requirements

### ISSUE THREAD

**Issue by demoyu123** [sstary/SSRS#41]
Hello, I see that there is no requirment.txt file provided in your FtransUNet, I don't know how to configure the environment of this project? So I'd like to ask you for advice. @sstary

**Comment by sstary** [comment]
你好，我们的模型并没有环境的特定需求，一般的pytorch版本都没有问题。只要能在你硬件上运行的pytorch环境应该都没有问题。

**Comment by demoyu123** [comment]
@sstary Thank you very much, I'll give it a try. Then there are no specific version requirements for these specific libraries in Python, right?

**Comment by sstary** [comment]
Yes. That's right.

**Comment by demoyu123** [comment]
> Yes. That's right.

Ok, thank you very much for your help.
