### ISSUE TITLE
MBATA_GAN：数据集标签读取

### ISSUE THREAD

**Issue by YUHsss** [sstary/SSRS#42]
您好，请问一下我训练我的自己数据集，其中标签已经是灰度图，是不是只需要将eroded_labels那里改为(np.asarray(io.imread(LABEL_FOLDER_V.format(id)), dtype='uint8') for id in test_ids_V) （我利用的您提供的DA_PRGB2V代码），或者还需要有其它修改的地方吗

**Comment by sstary** [comment]
你好，你说的灰度图是什么样的值呢？单通道的，只包含01,2,3,4，...，N 这种吗？如果是的话，是这样的，测试部分改成这样是OK 的，但是训练部分也要改，实际训练读取标签的代码在SSRS/MBATA_GAN/utils.py 187行。

**Comment by sstary** [comment]
另外，不知道你是否看了本仓库另一个工作GLGAN（https://arxiv.org/abs/2404.04531），我认为这是一个比MBATA-GAN更好的方法，或许它对你来说更有用。

**Comment by sstary** [comment]
1. 直接去掉应该就可以，如果数据类型不对，应该会报错的。
2. OK，希望对你有帮助。

**Comment by YUHsss** [comment]
你好，我想请教一个问题，就是我的影像是4通道的，我需要用到4个通道信息，所以我将backbone的输入通道改成了4，但是提示加载预训练权重时显示第一层不对，因此我在加载权重时设置了strict=False，这样的话合适吗，还是说直接不加载预训练权重

**Comment by sstary** [comment]
你好，这样可以的，这样只会去掉第一层输入层，影响不大，同时能保证大量预训练参数被用上。
