### ISSUE TITLE
Model Complexity：Hello, how do you measure FLOPs, Parameters, and Memory?

### ISSUE THREAD

**Issue by Gcx0707** [sstary/SSRS#44]
Hello, how do you measure FLOPs, Parameters, and Memory?

**Comment by sstary** [comment]
hello, you can refer to this link: https://blog.csdn.net/qq_45359549/article/details/134813792.
The memory usage: You can loop the model and record memory usage information using cmd nvidia-smi.

**Comment by Gcx0707** [comment]
> hello, you can refer to this link: https://blog.csdn.net/qq_45359549/article/details/134813792. The memory usage: You can loop the model and record memory usage information using cmd nvidia-smi.

Thank you for your reply.
