### ISSUE TITLE
数据集输入尺寸问题

### ISSUE THREAD

**Issue by Turanser** [sstary/SSRS#45]
数据集的训练图片尺寸是256×256，我该去哪部分的代码做修改？期待你的回复！

**Comment by Turanser** [comment]
我们的任务是二分类，只有一种目标区域，用这个模型做为对比，效果如何？

**Comment by sstary** [comment]
理论上应该是可以的，毕竟我们并未针对任务类别进行设计，而是一种更通用的模型上的改进。具体结果需要你自己实验验证。
