### ISSUE TITLE
软件包版本

### ISSUE THREAD

**Issue by terhh996** [sstary/SSRS#46]
请问一下tqdm跟pytorch版本？
pytorch1.13似乎会有很多错误
训练第一轮到百分之50的时候，进度条不显示，会有错误

**Comment by sstary** [comment]
你好，

我们的所有方法都不要求特定的tqdm和pytorch的版本。你这里应该是其他原因导致的。

你跑的哪个模型呢？具体log可以发给我看看吗？


________________________________
From: 吴春君（Wu Chunjun） ***@***.***>
Sent: Tuesday, October 29, 2024 4:38 PM
To: sstary/SSRS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sstary/SSRS] 软件包版本 (Issue #46)


请问一下tqdm跟pytorch版本？
pytorch1.13似乎会有很多错误
训练第一轮到百分之50的时候，进度条不显示，会有错误

―

**Comment by terhh996** [comment]
![Uploading 2024-10-29 17-02-59 的屏幕截图.png…]()
每次运行到这里都会出现错误的进度条，运行一段后会出现已杀死的提示
![Uploading 2024-10-29 17-02-59 的屏幕截图.png…]()

**Comment by terhh996** [comment]
![2024-10-29 17-02-59 的屏幕截图](https://github.com/user-attachments/assets/642c97a5-84ed-4910-ab5d-f3b74b45ece2)

**Comment by sstary** [comment]
你好，

看样子你是用RS3Mamba在LoveDA数据集上训练，这里你是断在了第一轮的测试中，并不是训练阶段。
这里断掉是因为第一轮训练之后的测试阶段，加载的测试集太多了， 你可以在Vaihingen数据集上跑一下，应该是没有问题的。
在LoveDA上，你可以把测试集删去一部分，将667张减少为300张应该是可以跑起来的，这样同样可以筛选出最好的模型，最后的最佳模型可以单独使用test函数，对667张图像进行完整的测试。

祝顺利，
献平
________________________________

**Comment by terhh996** [comment]
![2024-10-29 17-27-46 的屏幕截图](https://github.com/user-attachments/assets/1c000fbb-5bbb-4d54-a16f-77cc5163634f)

![2024-10-29 17-28-54 的屏幕截图](https://github.com/user-attachments/assets/51902fd9-0ed7-4064-b40a-6a3a77e4fd32)
这个问题需要修改吗？

**Comment by sstary** [comment]
警告不用管。
________________________________

**Comment by terhh996** [comment]
![2024-10-29 18-00-04 的屏幕截图](https://github.com/user-attachments/assets/f297ed57-6c98-4458-9da8-f6b9198f68b5)
似乎还是不太行 麻烦您能帮忙看一下吗

**Comment by terhh996** [comment]
感谢帮助 目前代码已经可以运行 只是进度条还是错误 这个我再仔细看一下 非常感谢你对我这个小白的帮助 祝生活顺利

**Comment by Oriongzx** [comment]
> 你好，
> 
> 看样子你是用RS3Mamba在LoveDA数据集上训练，这里你是断在了第一轮的测试中，并不是训练阶段。
> 这里断掉是因为第一轮训练之后的测试阶段，加载的测试集太多了， 你可以在Vaihingen数据集上跑一下，应该是没有问题的。
> 在LoveDA上，你可以把测试集删去一部分，将667张减少为300张应该是可以跑起来的，这样同样可以筛选出最好的模型，最后的最佳模型可以单独使用test函数，对667张图像进行完整的测试。
> 
> 祝顺利，
> 献平
> […](#)

![Image](https://github.com/user-attachments/assets/68f9e1af-9b0d-4e51-ad6d-2223364ecbd0)

你好，我也是有进度条问题，我使用的是loveDA数据集，我已经将测试集减少到53张图片，可是在测试过程中还是加载不出进度条，虽然最后会输出混淆矩阵，请问有没有什么办法可以解决，另外，能否在训练完毕后将log保存为txt文件，感谢！
