### ISSUE TITLE
数据集采样问题

### ISSUE THREAD

**Issue by terhh996** [sstary/SSRS#48]
数据集我换成了自己的数据集，尺寸为256×256，tif格式的图片，标签为同样尺寸格式的二分黑白图片，用于二分类
代码会报错
请问RS3Mamba支持256×256的训练数据集输入吗？
如果支持的话，请问有哪部分需要修改呢？
![2024-10-30 17-46-07 的屏幕截图](https://github.com/user-attachments/assets/a61a1dbd-9a53-43a7-bdb0-c3c73fa1abaa)

**Comment by terhh996** [comment]
我已经找到了问题所在 你的代码是多目标区域分割 我的数据集只有一个目标区域需要分割 所以造成错误 请问如何解决这个问题呢？

**Comment by sstary** [comment]
理论上，你之前截图的问题是我上一封邮件回复的注释掉188--191行，并将194行改成data_p, label_p = self.data_augmentation(data, label)，因为该截图报错的内容是那一部分引起的。貌似你没收到这部分的回信？
________________________________

**Comment by sstary** [comment]
我最近github账户登录出了问题，目前都是通过邮件直接回复的，可能会有消息的丢失。明天应该能解决登录问题，到时候会更方便。

________________________________

**Comment by terhh996** [comment]
我的数据集标签是黑白的RGB图像 是不是需要转换成灰度图 我在做这部分工作

**Comment by sstary** [comment]
一般你可以通过报错信息的最后几行，去查看对应的文件和函数，并根据你实际情况（比如你这里就是因为你的大图就是256*256，不需要使用滑动窗口裁剪），去理解其为什么出现问题。
________________________________

**Comment by sstary** [comment]
黑白色就是000 和 255 255 255 的双色三通道图像嘛，我看你修改色盘的操作是对的，你都走到get_random_pos这个函数了，说明你数据读取已经没问题了。
________________________________

**Comment by terhh996** [comment]
出现了这个问题
麻烦问一下怎么解决?
![2024-10-31 19-39-01 的屏幕截图](https://github.com/user-attachments/assets/543b24f6-ce3e-4808-892c-993e5c078226)




../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [27,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [28,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [29,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [30,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [31,0,0] Assertion `t >= 0 && t < n_classes` failed.

train_Mamba.py:None (train_Mamba.py)
train_Mamba.py:154: in <module>
    train(net, optimizer, 10, scheduler)
train_Mamba.py:123: in train
    loss.backward()
../../../.local/lib/python3.8/site-packages/torch/_tensor.py:487: in backward
    torch.autograd.backward(
../../../.local/lib/python3.8/site-packages/torch/autograd/__init__.py:197: in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
E   RuntimeError: numel: integer multiplication overflow
collected 0 items / 1 error

**Comment by terhh996** [comment]
出现了这个问题
 麻烦问一下怎么解决?
 
 
../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [27,0,0] Assertion t &gt;= 0 &amp;&amp; t < n_classes failed.
 ../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [28,0,0] Assertion t &gt;= 0 &amp;&amp; t < n_classes failed.
 ../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [29,0,0] Assertion t &gt;= 0 &amp;&amp; t < n_classes failed.
 ../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [30,0,0] Assertion t &gt;= 0 &amp;&amp; t < n_classes failed.
 ../aten/src/ATen/native/cuda/Loss.cu:242: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [31,0,0] Assertion t &gt;= 0 &amp;&amp; t < n_classes failed.
 
train_Mamba.py:None (train_Mamba.py)
 train_Mamba.py:154: in 
 train(net, optimizer, 10, scheduler)
 train_Mamba.py:123: in train
 loss.backward()
 ../../../.local/lib/python3.8/site-packages/torch/_tensor.py:487: in backward
 torch.autograd.backward(
 ../../../.local/lib/python3.8/site-packages/torch/autograd/init.py:197: in backward
 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
 E   RuntimeError: numel: integer multiplication overflow
 collected 0 items / 1 error




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sstary/SSRS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月31日(星期四) 晚上7:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sstary/SSRS] 数据集尺寸问题 (Issue #48)





 黑白色就是000 和 255 255 255 的双色三通道图像嘛，我看你修改色盘的操作是对的，你都走到get_random_pos这个函数了，说明你数据读取已经没问题了。 
 ________________________________

**Comment by sstary** [comment]
这个代表你计算loss时，模型输出的类别数，和你标签的类别数不等，你这里应该都是2才对。你检查一下所有的n class。如果这个没问题，那就是读取标签有问题，你可以在计算loss那一步打断点调试一下检查数据。
