### ISSUE TITLE
FTransUNet：Parameter

### ISSUE THREAD

**Issue by YYDS-cc** [sstary/SSRS#51]
感谢开源！
我想咨询下FTransUNet中有关参数量的问题。
为什么用 [(https://blog.csdn.net/qq_45359549/article/details/134813792)]这里的代码计算出来的参数量和复杂度与文章中的不一样呢？而且在运行python train.py 的时候代码中计算得到的参数量和文中的也不一致。

**Comment by sstary** [comment]
请问你计算得到的多少呢？
模型复杂度受硬件环境、输入图像batch size等的影响，你在同一个环境下评估即可。
模型参数可能是因为我后期测量时调整过N1 + N2 + N3的总数而在表VIII中记录了更小规模的值，你也可以根据你需要的进行调整。

**Comment by YYDS-cc** [comment]
好的了解了，谢谢师兄

**Comment by sstary** [comment]
不客气，感谢你的提醒。我们会在代码中增加相应的说明以避免该typo误导读者。
