### ISSUE TITLE
FTransUNet: 预训练权重

### ISSUE THREAD

**Issue by FengHaixia258** [sstary/SSRS#56]
请问可以提供./pretrain/R50+ViT-B_16.npz 这个预训练权重吗？

**Comment by FengHaixia258** [comment]
![微信图片_20241113224447](https://github.com/user-attachments/assets/059ab31c-6a60-4bc6-aa0a-fa5240740f83)

**Comment by sstary** [comment]
you can get the pre-trained model here: https://console.cloud.google.com/storage/browser/vit_models
in the folder: vit_models/imagenet21k/
