### ISSUE TITLE
LoveDA：eroded_labels

### ISSUE THREAD

**Issue by DerowPeng** [sstary/SSRS#57]
```    
if DATASET == 'Urban':
        eroded_labels = ((np.asarray(io.imread(ERODED_FOLDER.format(id)), dtype='int64') - 1) for id in test_ids)
```
there is no eroded_label in loveDA datasets, is there any link to the eroded_labels in loveDA?

**Comment by DerowPeng** [comment]
so, in `RS3Mamba/util_Mamba.py`,  `LABEL_FOLDER` and ` ERODED_FOLDER` are the same?
thanks u

**Comment by sstary** [comment]
Yes, as the lines 71-72 in utilis_mamba.py:
    LABEL_FOLDER = MAIN_FOLDER + 'masks_png/{}.png'
    ERODED_FOLDER = MAIN_FOLDER + 'masks_png/{}.png'

**Comment by sstary** [comment]
If there is any help to you, please give me a star.
THANK YOU.

**Comment by derow0208** [comment]
thank you for your excellent work!
