### ISSUE TITLE
No pre-training weight

### ISSUE THREAD

**Issue by OrangeCat12352** [sstary/SSRS#6]
Hello, I got some inspiration from your paper and am trying to replicate your method with FTransUNet. However, I found that the pre-training weights were missing. Can you provide the pre-training weight files? Thank you for sharing

**Comment by sstary** [comment]
I'm very glad to here that. Our method is based on TransUNet, so you can get the pre-trained model here: https://github.com/Beckschen/TransUNet?tab=readme-ov-file
