### ISSUE TITLE
Urban：Barren

### ISSUE THREAD

**Issue by Gcx0707** [sstary/SSRS#60]
Hello, I have started training with the LoveDA Urban dataset, why is the barren class almost zero after 50 iterations? It was normal with the Vaihingen dataset, do I need to modify some code in train_Mamba or utils_Mamba?

**Comment by sstary** [comment]
Are you using RS3Mamba? The two data sets do not require special processing. Do you have this problem with other models?

**Comment by Gcx0707** [comment]
> Are you using RS3Mamba? The two data sets do not require special processing. Do you have this problem with other models?

https://github.com/sstary/SSRS/issues/60#issuecomment-2487367867

**Comment by sstary** [comment]
？

**Comment by Gcx0707** [comment]
> ？

My apologies, I only used a small part of the test set and did not conduct a full validation.

**Comment by sstary** [comment]
okkkk
