### ISSUE TITLE
SAM_RS中的BoundaryLoss计算

### ISSUE THREAD

**Issue by wansdd** [sstary/SSRS#63]
您好，当我运行sam_rs的训练脚本训练Vaihingen数据集时，遇到
       return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: "max_pool2d" not implemented for 'Long
![image](https://github.com/user-attachments/assets/680ac742-5009-4af6-85fc-5db8a1bd0f44)
所以我找到对应计算max_pool2d的地方对数据进行了转换
![image](https://github.com/user-attachments/assets/229d2a6e-7809-4925-94ae-6c6557f69780)
再次运行训练脚本时遇到了
  File "/Programs/SSRS/SAM_RS/utils.py", line 441, in forward
    P = torch.sum(pred_b * gt_b_ext, dim=2) / (torch.sum(pred_b, dim=2) + 1e-7)
RuntimeError: The size of tensor a (32768) must match the size of tensor b (98304) at non-singleton dimension 2
![image](https://github.com/user-attachments/assets/2be13b23-f07a-46c7-b781-5ca2d183bb88)
请问这块是哪里出问题了
这是我的torch版本
![image](https://github.com/user-attachments/assets/052a72f1-3a62-49ee-84f0-0c12b1bf7470)

**Comment by wansdd** [comment]
我发现是我sam预处理时出了问题

**Comment by Steveehui** [comment]
遇到了同样的问题，现在尝试对预处理文件sam_utils进行修改，请问最后是进行了哪部分的修改
