### ISSUE TITLE
FTransUNet：训练时卡住

### ISSUE THREAD

**Issue by ymmyys** [sstary/SSRS#64]
Train (epoch 1/50) [0/1000 (0%)]	Loss: 1.958552	Accuracy: 10.37750244140625
卡在第一个epoch之后就不运行了是为什么，以及模型里的2d交叉熵函数还有多处地方产生warning，框架太老了

**Comment by sstary** [comment]
你可以把打印频率调到每一个batch打印一次检查一下到底卡在哪一步，或者直接debug看看。warning不影响运行。你也可以直接把模型移到你觉得的更新的框架中，如mmsegmentation等。

**Comment by ymmyys** [comment]
> 你可以把打印频率调到每一个batch打印一次检查一下到底卡在哪一步，或者直接debug看看。warning不影响运行。你也可以直接把模型移到你觉得的更新的框架中，如mmsegmentation等。

 NVIDIA GeForce RTX 3060 Laptop GPU需要训练多久？我用的自己的笔记本跑，他好像也没有卡，就是运行的很慢？

**Comment by sstary** [comment]
你检查下是否运行了gpu，如果运行了gpu，最多几分钟就有100个batch，就会打印输出。
