### ISSUE TITLE
MFNet：代码反向传播有问题

### ISSUE THREAD

**Issue by liting1018** [sstary/SSRS#66]
发生异常: RuntimeError
GET was unable to find an engine to execute this computation
  File "MFNet/train.py", line 157, in train
    loss.backward()
  File "MFNet/train.py", line 193, in <module>
    train(net, optimizer, epochs, scheduler, weights=WEIGHTS, save_epoch=save_epoch)
RuntimeError: GET was unable to find an engine to execute this computation
请问应该如何解决呢？

**Comment by sstary** [comment]
这应该是环境的问题，请参考：https://blog.csdn.net/qq_33431368/article/details/131318202。

**Comment by liting1018** [comment]
感谢您的回复，已解决！

**Comment by sstary** [comment]
如果有帮助，请点个star！

**Comment by liting1018** [comment]
OK
