### ISSUE TITLE
MFNet：结果较低

### ISSUE THREAD

**Issue by ljtjy** [sstary/SSRS#67]
作者您好，我查阅MFNet代码发现提供了Lora和Adapter两种微调方法，我按下面步骤在Vaihingen上复现Adapter方法：
1.使用cfg.py中  parser.add_argument('-mod', type=str, default='sam_adpt', help='mod type:seg,cls,val_ad')这句代码，注释  parser.add_argument('-mod', type=str, default='sam_lora', help='mod type:seg,cls,val_ad')这句代码
2.train.py和Unetformer_MMSAM.py中修改冻结image_encoder参数代码为：
for name, param in net.image_encoder.named_parameters():
    if "Adapter" not in name:
        params1 += param.nelement()
    else:
        params2 += param.nelement()
得到最优mIOU为71.83  请问是我的步骤出错了吗

**Comment by sstary** [comment]
你好，train文件的注释是为了统计参数量，Unetformer_MMSAM文件中的注释十分重要，是固定SAM原权重并且微调Adapter分支，cfg是针对MedSAM目录下选择对应的方法。正常情况下你这个设置应该没问题了，你可以把log发我邮件，并且自己debug一下运行代码是不是正确调用了MedSAM内部的Adapter模块。

**Comment by liting1018** [comment]
楼上说的第二点应该不对吧，那个只是统计参数量。请问固定SAM原权重并且微调Adapter分支代码是在哪一部分呢？另外文中说的两个分支是共享参数的，我读的代码是定义并使用两个独立的分支计算x和y，请问哪里体现共享了呢？
希望作者解答下呢，感谢！

**Comment by sstary** [comment]
你好，第二点去一个mmsam文件定义中那里，我说固定sam权重并微调adapter分支这一点吗？若是，那么这一点是没错的，在那个判断语句中，模块定义不含有“adapter”字母（也就是原来SAM）所有的模块都是不保留梯度的，自然不会更新，而只有微调模块会更新。
另外所谓的共享也就是上述的不微调的sam分支，这个分支会同时处理x和y，具体可以去medsam目录内部adapterblock里去看。
有问题欢迎继续讨论。

**Comment by liting1018** [comment]
> 你好，第二点是指Unetformer_MMSAM文件定义中那里，我说固定sam权重并微调adapter分支这一点吗？若是，那么这一点是没错的，在那个判断语句中，模块定义不含有“adapter”字母（也就是原来SAM）所有的模块都是不保留梯度的，自然不会更新，而只有微调模块会更新。 另外所谓的共享也就是上述的不微调的sam分支，这个分支会同时处理x和y，具体可以去medsam目录内部adapterblock里去看。 有问题欢迎继续讨论。

您好，请问您使用的decoder是自己重写的嘛，我看和SAM中的decoder结构并不一致？为什么不用sam decoder呢？

**Comment by sstary** [comment]
你好，你可以看一下我的arxiv的文章，我个人认为SAM的参数集中在编码器，所以通用知识基本集中在编码器上，且SAM的编码器只能输出无语义分割的mask，所以我采用了SAM的编码器，以及遥感领域一个效果很好的解码器（UNetformer），这样我们的方法将更具有可扩展性，能很方便的通过更换解码器适应于各种任务，包括但不限于语义分割、变化检测、目标检测等。

**Comment by liting1018** [comment]
> 你好，你可以看一下我arxiv文章中，简介部分的相关论述，我个人认为SAM的参数集中在编码器，所以通用知识基本集中在编码器上，且SAM的编码器只能输出无语义分割的mask，所以我采用了SAM的编码器，以及遥感领域一个效果很好的解码器（UNetformer），这样我们的方法将更具有可扩展性，能很方便的通过更换解码器适应于各种任务，包括但不限于语义分割、变化检测、目标检测等。

明白了，感谢！

**Comment by ljtjy** [comment]
您好，在arxiv文章表VI中MANet(vit-l)那一行请问mIoU结果正确吗，其中参数量我运行是这个结果，有一些出入。
All Params:    364955646
ImgEncoder:    308278272
Adapter:        50454576
Others:  6222798

**Comment by sstary** [comment]
你是目前还没有跑出和我接近的MIoU是吗？
只在Vit-l上试过？
你的MIoU大概是怎么样的？差了很多的话可以把你的log通过邮箱发我看下。

**Comment by sstary** [comment]
此外，我想问下，你本地跑出来的结果和我报告的结果接近吗？
