### ISSUE TITLE
ASMFNet：权重

### ISSUE THREAD

**Issue by 1000xLukaoo** [sstary/SSRS#69]
请问ASMFNet权重在哪下载？
还有这个权重下ASMFNet可以训练512×512的数据的吗，需要改动哪些地方？
谢谢！

**Comment by sstary** [comment]
你好，请在Swin Transformer 的仓库下载：https://github.com/microsoft/Swin-Transformer?tab=readme-ov-file。Train文件中使用的上：https://github.com/SwinTransformer/storage/releases/download/v1.0.8/swin_tiny_patch4_window7_224_22k.pth

另外，本文由于投稿不顺利，使用的方法已经偏久远了，如果你研究的上多模态任务，我建议你尝试我们最新的方法MFNet。

**Comment by 1000xLukaoo** [comment]
谢谢 不过刚试了下MFNet 请问它的推理速度相比FTransUNet是会慢很多吗？

**Comment by sstary** [comment]
不会。由于不会训练SAM固定分支，推理速度和内存占用都更小。
