### ISSUE TITLE
关于FtransUNet的数据集问题 

### ISSUE THREAD

**Issue by luy0222** [sstary/SSRS#7]
作者你好，请问你的Vaihingen的DSM图像是怎么获得的，我下载的数据集DSM图像是一片空白
![e38e38df33f4da3985034b6ac0df1eb](https://github.com/sstary/SSRS/assets/124013402/48ff69c8-4098-4afb-8a46-39f426922083)

**Comment by sstary** [comment]
你好，DSM数据可以使用ArcGIS等地理学软件打开，此外你可以使用python tifffile包读取，其值并不在0-255之间，需要归一化处理。

**Comment by luy0222** [comment]
感谢您的回复！我还是有点问题，代码中放入DSM数据的是处理好的数据吗？还是放入空白的DSM图像？
![1710661107905](https://github.com/sstary/SSRS/assets/124013402/e6772df5-0018-46d4-8ec3-909d861c85d9)
我放入空白的DSM图像复现的结果和论文中的数值有点偏差。
![fd8705a62c5fb019e86d8f5e1486ad5](https://github.com/sstary/SSRS/assets/124013402/d97d9d2a-a181-41cf-b333-06ea21efa56f)

**Comment by sstary** [comment]
你好，我们并未对DSM做任何预处理，直接使用了官方提供的‘dsm_09cm_matching_area*’前缀的数据，所有的操作均在上传的代码中；另实验结果本身存在一定的波动性，在你自己的环境中公平的实验即可。

**Comment by luy0222** [comment]
我已经找出相应代码了，感谢您的耐心回复！

**Comment by zhangyubo1021** [comment]
你好请问FTransUNet数据集是怎么处理 的，还有请问如何获取DSM图像

**Comment by sstary** [comment]
你好，ISPRS的完整数据集可从 https://github.com/open-mmlab/mmsegmentation/blob/main/docs/en/user_guides/2_dataset_prepare.md 下载。
具体处理读取方式在utils.py文件中，该过程不需要任何额外的预处理操作，直接运行即可。

**Comment by zhangyubo1021** [comment]
已经跑通了谢谢你，还有一个问题就是为什么生成的热力图都是空白颜色的您能解答一下吗

**Comment by sstary** [comment]
请使用heatmap_test.py进行绘制。该文件最近才更新，你可能需要重新pull一下。如有问题，请先调试改文件试试

**Comment by zhangyubo1021** [comment]
好的谢谢你我再试一试
