### ISSUE TITLE
FTransUnet：训练时加载验证集相关问题

### ISSUE THREAD

**Issue by duan43560096** [sstary/SSRS#71]
尊敬的作者，您好！我是刚开始学习深度的学习的小白，对大佬您的工作十分感兴趣，在运行您的代码的时候，跑完500次之后，进入验证集，出现下面的这种情况
![微信图片_20241210100422](https://github.com/user-attachments/assets/04806d65-9477-4b4c-9871-c975e166c052)
想请问下，这几个进度条为0的是什么情况？期待您的回复，十分感谢！

**Comment by sstary** [comment]
你好，十分感谢你的关注。这是正常的，在log打印的过程中测试阶段每张大图只会静态输出一次，实际已经正常测试了，后面四张图测试完就会输出总体指标。
麻烦点个star。

**Comment by duan43560096** [comment]
感谢，您的回复，我意识到整个代码在正常训练，请问这样进度条为0的情况是tqdm的显示bug吗？

**Comment by sstary** [comment]
你好，这不能算是显示bug，因为log是静态文本，如果tqdm每个1%都输出一次，你可以想象这部分得打印多长，这应该和linux的缓存输出机制有关，具体我也没深入关注过。而在动态窗口界面执行的时候就可以显示动态的进度条。

**Comment by duan43560096** [comment]
谢谢您！我明白您的意思了，十分感谢您的解答。祝您生活愉快，科研顺利！

**Comment by duan43560096** [comment]
> 你好，十分感谢你的关注。这是正常的，在log打印的过程中测试阶段每张大图只会静态输出一次，实际已经正常测试了，后面四张图测试完就会输出总体指标。 麻烦点个star。
已点star，忘说了
