### ISSUE TITLE
FTransUnet：训练时间过长

### ISSUE THREAD

**Issue by hxx0604** [sstary/SSRS#72]
您好，我使用的是NVIDIA GeForce RTX 3090，想问一下您训练一个epoch大概需要多久呀，我要一个小时才训练一个epoch，这是正常的吗？谢谢

**Comment by sstary** [comment]
你好，一般几分钟100个batch，就会输出一次log，测试时间视数据集大小有差异，vaihingen测试估计十多分钟，所以一整个epoch大概20分钟。
你哪一步很慢呢？哪个数据集？

**Comment by hxx0604** [comment]
> 你好，一般几分钟100个batch，就会输出一次log，测试时间视数据集大小有差异，vaihingen测试估计十多分钟，所以一整个epoch大概20分钟。 你哪一步很慢呢？哪个数据集？

用的Potsdam数据集，
![image](https://github.com/user-attachments/assets/f877261c-1e09-4b77-8a89-4d2d9eff0bb8)

**Comment by sstary** [comment]
需要注意的是，如果是potsfam数据集，测试的时候步长要设置为128，这样测试更快。
你这一个小时也不算太夸张，如果显卡有别人也在跑，一个小时一个epoch也差不多。

**Comment by sstary** [comment]
你截个测试阶段的图，我看看你测试的步长是多少。不过就算是128，它测试也很慢，3090差不多就一个小时。

**Comment by hxx0604** [comment]
> 需要注意的是，如果是potsdam数据集，测试的时候步长要设置为128，这样测试更快。 你这一个小时也不算太夸张，如果显卡有别人也在跑，一个小时一个epoch也差不多。

好滴，非常感谢回复，我是科研小白，我想请问下，就是在保存模型时，是要先建好对应的目录吗，这样才能保存？因为我第一次训练的时候，在第5个epoch时，他的精度已经达到了90%，但是发现并未保存模型，也未报错

**Comment by sstary** [comment]
> > 你截个测试阶段的图，我看看你测试的步长是多少。不过就算是128，它测试也很慢，3090可能会一个小时。可以通过减少测试频率来提高速度，一般最佳性能出现在25epoch左右。
> 
> ![image](https://private-user-images.githubusercontent.com/85691032/396803454-842a91dd-f620-437c-9174-dea7339ad7b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDgwNDEsIm5iZiI6MTczNDUwNzc0MSwicGF0aCI6Ii84NTY5MTAzMi8zOTY4MDM0NTQtODQyYTkxZGQtZjYyMC00MzdjLTkxNzQtZGVhNzMzOWFkN2I1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA3NDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMzA1MGYzZTIxNDNkOWE4YTZlMmQ5NmM0Mzk2ZTI1YzAyMmI3MGRkMDE1YmM5YTFiNzk2MDQ5MWNhMDkzNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aqpgGe2tL5Y9QTWUB-MTzr0eXGwsPhgAfbQ8JxMD51k) c测试步长就是128

那就是正常的，你使用Vaihinge就不会这么慢，一般我跑Potsdam完整跑完也得一两天的。你可以改一下测试频率，比如epoch在20以后每轮测一次，这样就会极大提高测试效率。

**Comment by sstary** [comment]
> > 需要注意的是，如果是potsdam数据集，测试的时候步长要设置为128，这样测试更快。 你这一个小时也不算太夸张，如果显卡有别人也在跑，一个小时一个epoch也差不多。
> 
> 好滴，非常感谢回复，我是科研小白，我想请问下，就是在保存模型时，是要先建好对应的目录吗，这样才能保存？因为我第一次训练的时候，在第5个epoch时，他的精度已经达到了90%，但是发现并未保存模型，也未报错

是的，需要先创建对应目录。另外，我在代码中设置了best_MIoU这个参数，模型需要超过这个值才会保存，精度（Accuracy）这个参数没有MIoU这个参数更可靠，因此，我们以MIoU为准。你可以看下代码中设置的阈值。

**Comment by hxx0604** [comment]
> > > 需要注意的是，如果是potsdam数据集，测试的时候步长要设置为128，这样测试更快。 你这一个小时也不算太夸张，如果显卡有别人也在跑，一个小时一个epoch也差不多。
> > 
> > 
> > 好滴，非常感谢回复，我是科研小白，我想请问下，就是在保存模型时，是要先建好对应的目录吗，这样才能保存？因为我第一次训练的时候，在第5个epoch时，他的精度已经达到了90%，但是发现并未保存模型，也未报错
> 
> 是的，需要先创建对应目录。另外，我在代码中设置了best_MIoU这个参数，模型需要超过这个值才会保存，精度（Accuracy）这个参数没有MIoU这个参数更可靠，因此，我们以MIoU为准。你可以看下代码中设置的阈值。

好滴好滴，十分感谢，已star

**Comment by hxx0604** [comment]
![image](https://github.com/user-attachments/assets/1e11aa54-efbd-4731-af5d-bed7ae5ed073)

你好，又来打扰你了，你可以帮我看一下Vaihingen数据集这样对应对吗，此外，我没有找到gts_eroded_for_participants这个文件，那gts_eroded_for_participants文件指的是下面图片对应的这个文件夹吗，我看这个文件夹里对应的后缀是对应的，我不是很确定，想来问问你。谢谢啦
![image](https://github.com/user-attachments/assets/8b6e250d-aa0d-4d2d-a71d-eb051cea5d64)

**Comment by sstary** [comment]
那就应该没问题，可能数据集更新过名字。只要里面图片的内容是没问题的就好了，你也可以和LABEL_FLODER里的图片打开作对比，这个eroded的就是对边界进行了特殊处理，会变成黑边，你可以检查下。

**Comment by hxx0604** [comment]
> 那就应该没问题，可能数据集更新过名字。只要里面图片的内容是没问题的就好了，你也可以和LABEL_FLODER里的图片打开作对比，这个eroded的就是对边界进行了特殊处理，会变成黑边，你可以检查下。

![image](https://github.com/user-attachments/assets/4371d499-025c-4a25-a3c6-901473beae27)
是这样的吗

**Comment by hxx0604** [comment]
> 那就应该没问题，可能数据集更新过名字。只要里面图片的内容是没问题的就好了，你也可以和LABEL_FLODER里的图片打开作对比，这个eroded的就是对边界进行了特殊处理，会变成黑边，你可以检查下。

那应该是没问题的，谢谢您的回复！！！

**Comment by sstary** [comment]
OK

**Comment by hxx0604** [comment]
> 建议你在Vaihingen上做实验，这样更快。 另外也建议你采用我们最新的方法MFNet，这是一个更好的模型，相比FTransUNet，在模型复杂度和性能上都有提升。结合了大模型，也更具有吸引力。

非常感谢告知，我下载的是以前的代码所以没看到，我再重新下拉一下代码，感谢感谢！！！

**Comment by hxx0604** [comment]
你好，我在vaihingen数据集上训练之后进行测试，为什么准确率这莫低呀，每一个类别的准确率都挺低的。
![image](https://github.com/user-attachments/assets/9af5683c-9811-4844-8a10-a15e9b890272)

**Comment by hxx0604** [comment]
> 你好，我在vaihingen数据集上训练之后进行测试，为什么准确率这莫低呀，每一个类别的准确率都挺低的。 ![image](https://private-user-images.githubusercontent.com/85691032/397602631-9af5683c-9811-4844-8a10-a15e9b890272.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NjQ4NTAsIm5iZiI6MTczNDY2NDU1MCwicGF0aCI6Ii84NTY5MTAzMi8zOTc2MDI2MzEtOWFmNTY4M2MtOTgxMS00ODQ0LThhMTAtYTE1ZTliODkwMjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDAzMTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZDJhZTBjYzYzYzdjYWU4NTk1ODY5ZGVhZjQ2Njk5ZDViNjUxNmFlOThlOWY5MDY3ODJjZTkwMGIwNDI0ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k72PobhTQeetvDJKHDZoRvzvU8Ij3whUC9ab3idsExU)

可能在不同电脑上跑出来，结果有差异，但是感觉结果差的有点多，这是正常的吗

**Comment by sstary** [comment]
不正常，环境误差大概在1%左右，即miou可能波动一点，但是不会差这么多。
你把log的最开始那段输出贴一下。

**Comment by sstary** [comment]
你预训练模型加载了吗？数据集、训练、测试等相关超参和我设置的一致吗？

**Comment by hxx0604** [comment]
![image](https://github.com/user-attachments/assets/39c5a0be-b76c-43b4-8ea8-be88a0fc9ca2)
![image](https://github.com/user-attachments/assets/31cdf25c-185a-41a3-9b3c-e233f11cf3a5)
麻烦看一下呢

**Comment by hxx0604** [comment]
> 你预训练模型加载了吗？数据集、训练、测试等相关超参和我设置的一致吗？

预训练模型加载了，数据集、训练、测试等相关超参我没改动

**Comment by hxx0604** [comment]
> 你预训练模型加载了吗？数据集、训练、测试等相关超参和我设置的一致吗？

![image](https://github.com/user-attachments/assets/ce5a5cbb-d8cc-4b4b-bd33-a9c47eb67dee)

**Comment by sstary** [comment]
你训练的batch size是1吗？应该是10。

**Comment by hxx0604** [comment]
> 你训练的batch size是1吗？应该是10。 你加载的这个模型是自己训练得到的？

那我把batch size改成10 再试一下，加载的模型是自己训练得到的。
感谢回复，谢谢

**Comment by sstary** [comment]
你用test_heatmap.py文件跑的训练？
应该用train.py文件跑的。

**Comment by hxx0604** [comment]
> 你用test_heatmap.py文件跑的训练？ 应该用train.py文件跑的。

训练的时候，我是用Train.py跑的，但是训练完不是要测试吗，我就在test_heatmap.py跑的。那个加载的模型也是在Train.py跑的时候加载的

**Comment by sstary** [comment]
我readme写的有点不清晰，我调整下，你等会可以去看看。

**Comment by hxx0604** [comment]
> 你用test_heatmap.py文件跑的训练？ 应该用train.py文件跑的。

训练的时候，用的是train.py，但是我想着训练完不是要测试吗，就用test_heatmap.py跑了一下呢

**Comment by hxx0604** [comment]
> 我readme写的有点不清晰，我调整下，你等会可以去看看。

好的，感谢啦

**Comment by sstary** [comment]
我更新了：
Run the code by: python train.py (Train and Test both in this file, but you need to choose the corresponding code.)

If you want to draw the heatmaps by: python test_heatmap.py
可能更清楚一点。

**Comment by hxx0604** [comment]
> 你用test_heatmap.py文件跑的训练？ 应该用train.py文件跑的。

如果我用test_heatmap.py跑，保存的结果不应该是热力图吗，但是我打开看怎么是一串乱码呀

**Comment by hxx0604** [comment]
> 我更新了： Run the code by: python train.py (Train and Test both in this file, but you need to choose the corresponding code.)
> 
> If you want to draw the heatmaps by: python test_heatmap.py可能更清楚一点。

就是测试和训练都在train.py,只有需要生成热力图的时候才需要跑test_heatmap.py。好的，我明白了，感谢感谢

**Comment by sstary** [comment]
你在linux上打开了pdf？如果是，下载到本地打开。

**Comment by hxx0604** [comment]
> 你在linux上打开了pdf？如果是，下载到本地打开。

好滴好滴，谢谢啦

**Comment by sstary** [comment]
正常训练应该这样：
![image](https://github.com/user-attachments/assets/59a0fc48-0ef3-47ac-a6cc-88a5f6f7e2ab)

**Comment by hxx0604** [comment]
> 正常训练应该这样： ![image](https://private-user-images.githubusercontent.com/28852884/397606843-59a0fc48-0ef3-47ac-a6cc-88a5f6f7e2ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NjYwODMsIm5iZiI6MTczNDY2NTc4MywicGF0aCI6Ii8yODg1Mjg4NC8zOTc2MDY4NDMtNTlhMGZjNDgtMGVmMy00N2FjLWE2Y2MtODhhNWY2ZjdlMmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDAzMzYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZGRkMTQwNTAzMjE4ZTU0YzgxYzQ2YzNkYjMxOWE5NmNjMGVmMjE5ZGMxMmUzY2I0ZGMxY2RhNDM5OWE3MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vRtIlH-xPmpbI2GVJrkuXirXjY1A4_4pVyP07QUEFv8)

我昨天训练的时候是这样的，谢谢啦

**Comment by sstary** [comment]
那你也是batch size 10训练的，不应该这么差才对。

**Comment by hxx0604** [comment]
> 那你也是batch size 10训练的，不应该这么差才对。

![image](https://github.com/user-attachments/assets/90ee2835-2e39-4528-82ba-a9b8e80b8c36)
这是昨天保存的模型的结果，我也不知道哪里出现了问题

**Comment by sstary** [comment]
你log里面最佳miou是多少，截个图看看

**Comment by sstary** [comment]
你加载的模型是91.62，测试出来只有90.51？
测试步长应该是32，打印是这样的：
![image](https://github.com/user-attachments/assets/f3e63c60-e980-46ba-8d4f-cee8d3fa6d48)

**Comment by hxx0604** [comment]
> 你log里面最佳miou是多少，截个图看看

![image](https://github.com/user-attachments/assets/a9ca5fac-cd21-402d-9409-bcea6cbf6fce)

**Comment by hxx0604** [comment]
> 你加载的模型是91.62，测试出来只有90.51？ 测试步长应该是32，打印是这样的： ![image](https://private-user-images.githubusercontent.com/28852884/397620225-f3e63c60-e980-46ba-8d4f-cee8d3fa6d48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NzEwMzUsIm5iZiI6MTczNDY3MDczNSwicGF0aCI6Ii8yODg1Mjg4NC8zOTc2MjAyMjUtZjNlNjNjNjAtZTk4MC00NmJhLThkNGYtY2VlOGQzZmE2ZDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA0NTg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYThiYjg4ZDQ2ODFkNDMwMDg0YWY2M2JhMTNhMDBmMmViYzg5MzY1ODM2M2FkZWQ4NzMzM2E0ZmQ0NWNhM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HacGseQVlC0LyvekJ078FMftIZs-gWzxsewQv7kEZbY)

和你的好像是一样的
![image](https://github.com/user-attachments/assets/35ca302c-a10d-4932-b2a1-d4c65561b64f)

**Comment by hxx0604** [comment]
> > 你log里面最佳miou是多少，截个图看看
> 
> ![image](https://private-user-images.githubusercontent.com/85691032/397621087-a9ca5fac-cd21-402d-9409-bcea6cbf6fce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NzE5MjIsIm5iZiI6MTczNDY3MTYyMiwicGF0aCI6Ii84NTY5MTAzMi8zOTc2MjEwODctYTljYTVmYWMtY2QyMS00MDJkLTk0MDktYmNlYTZjYmY2ZmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDA1MTM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNzc2YmY0YmM1OTY0NjQ2NmU0MDJmNzZlMTI0MjJjNDhjZjAxOGVhZjg0ZmQ4Y2I4ODE1ZDgzNDJlNDA4YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I3s62mUOqdQYh4k6w3hbVKqQkSDPYw2k10ADlkofHvw)

这是现在测试得到的结果，论文里的是下面这张图，那现在这个误差是正常的吗
![image](https://github.com/user-attachments/assets/eb814e11-47d3-4f14-ba34-5cb08e2017b1)

**Comment by sstary** [comment]
不正常，还是差太多了。你跑个unetformer试试。对比一下，看是你环境的问题还是FTransUNet的问题。

**Comment by hxx0604** [comment]
> 不正常，还是差太多了。你再跑一次看看。 你也可以跑个unetformer试试。对比一下，看是你环境的问题还是FTransUNet的问题。

行的，谢谢啦

**Comment by hxx0604** [comment]
你好，我现在准备跑UNetFormer，我看那个readme里的vaihingen数据集路径是这样摆放的，我不太清楚这个train_masks是指的那个数据呀，可以问一下你与哪个对应吗？感谢
![image](https://github.com/user-attachments/assets/baf9767c-c8b7-4e32-b167-524326ffa52a)
![image](https://github.com/user-attachments/assets/f8a6496d-96d3-4f4a-bce5-ef008c386365)

**Comment by sstary** [comment]
你不用去调用他的模型框架，直接在我那个框架里跑就行了。直接用UNetformer模型替换掉FTransUNet就好了，但是改一下UNetformer的forward，让它接收两个模态x和y，但是仅使用x即可。可以参考下SAM_RS/目录下模型的替换使用方式。

**Comment by hxx0604** [comment]
> 你不用去调用他的模型框架，直接在我那个框架里跑就行了。直接用UNetformer模型替换掉FTransUNet就好了，但是改一下UNetformer的forward，让它接收两个模态x和y，但是仅使用x即可。可以参考下SAM_RS/目录下模型的替换使用方式。

好滴好滴，谢谢大佬回复，我去研究研究
