### ISSUE TITLE
FTransUNet：代码运行问题

### ISSUE THREAD

**Issue by longzhe-csgo** [sstary/SSRS#73]
作者你好，
在运行代码的时候，出现这种报错，请问是什么原因导致的呢？

![Snipaste_2024-12-19_16-58-36](https://github.com/user-attachments/assets/943d7a20-2c05-4468-9407-3f5c02a532c6)

**Comment by longzhe-csgo** [comment]
非常感谢你的及时回复

**Comment by sstary** [comment]
有帮助请点个star！

**Comment by sstary** [comment]
另外也建议你采用我们最新的方法MFNet，这是一个更好的模型，相比FTransUNet，在模型复杂度和性能上都有提升。结合了大模型，也更具有吸引力。

**Comment by longzhe-csgo** [comment]
抱歉哈哈，太尴尬了，感谢你的建议，非常感谢。我是一个遥感领域的初学者，你的耐心回复给了我很大动力，感谢。

**Comment by sstary** [comment]
不客气，加油！

**Comment by longzhe-csgo** [comment]
你好，关于MFNet  可以给一个网址吗

**Comment by sstary** [comment]
也在本仓库，你可能需要重新pull一下：https://github.com/sstary/SSRS

**Comment by longzhe-csgo** [comment]
感谢！

**Comment by longzhe-csgo** [comment]
你好作者，我在服务器跑代码时出现了与本地不一样的错误，在连接ssh之后进行环境配置，我安装了scikit-image但是仍然会发现在程序中无法导入的错误  请问有相关解决的经验吗？
![Snipaste_2025-01-13_12-47-13](https://github.com/user-attachments/assets/993fb427-b7f7-4671-8e29-f3bd589e3996)

**Comment by sstary** [comment]
你好，报错提示是什么呢？无法找到/导入skimage吗？
我一般更喜欢用vscode，pycharm感觉比较麻烦。。。

**Comment by sstary** [comment]
你有选择对应的虚拟环境了吗？是不是安装的库的环境并没有调用？

**Comment by longzhe-csgo** [comment]
是的，显示**未解析的引用**。我刚开始也用了vscode 但是一直连接失败，所以才用了pycharm。我觉得应该使用了吧，在使用pycharm连接ssh的时候，我选择了系统环境。请问可能是服务器环境的问题吗，我等下换一个服务器试一试

**Comment by sstary** [comment]
你现在是用pycharm连接了linux的服务器？然后用不了是吗？
如果在linux上是可以用的吗？
如果是的话，你可以先用mobaxterm等软件通过ssh方式登录，直接用命令行的方式看看能不能运行，排除一下是虚拟环境的问题，还是你pycharm配置的问题。

**Comment by sstary** [comment]
看你这个报错，感觉skimage没有正确安装的可能性也挺大，如果是版本没对齐的话，应该是在运行时报错，而不是这种下划虚线（找不到库）的形式。

**Comment by longzhe-csgo** [comment]
你好作者，mfnet和ftransunet都已经运行成功了，抱歉没有及时回复。关于mfnet有一个小问题希望能解答一下，在mfnet文件夹中我看到medsam，我了解到这是一个关于医学图像分割适配的模型，我起初以为mfnet是以标准的sam进行微调的，所以我想问一下医学图像的模型也能够迁移到遥感领域吗  还是说要进行部分修改？感谢

**Comment by sstary** [comment]
mfnet就是以标准的sam进行微调的，你可以看下加载模型的部分，其预训练权重就是标准的sam。 medsam是因为微调技术来源于此，多模态策略由此改进而来。

**Comment by longzhe-csgo** [comment]
奥奥，明白了。原来是我代码还没有完全弄明白，感谢感谢！

**Comment by longzhe-csgo** [comment]
打扰了，我这边有一个问题希望您能抽空看一下，关于MFNet在DFM模块中你将encoder的特征图也就是维度为256*16*16，直接对他进行反卷积和卷积，我想问一下这会不会导致产生大量冗余的同质化语义信息，毕竟F1-F4都来源于同一个feature map。感谢您的帮助！

**Comment by sstary** [comment]
你好，这是Exploring Plain Vision Transformer Backbones for Object Detection的研究结果，此外，SAM采用的骨干网实际上也是这篇文章的结构，再此外，由于这种结构，也就是SAM编码器仅提供了最深尺度的特征图，想要得到多尺度特征这也是一个较好的方法。有些文章提取不同层再去上下采样，但是应该差别不会很大，因此，我们遵循Plain Vision Transformer 的研究结果。

**Comment by longzhe-csgo** [comment]
你好作者 请问在运行FTransunet时一个epoch之后的运行结果 cars的结果是没有的  这个应该是不正常的吧
请问这是由什么原因导致的呢？

![Image](https://github.com/user-attachments/assets/5545876b-0f81-4bc3-9c86-c7bcdd84ae65)

**Comment by sstary** [comment]
你好，

如果是第一个epoch，没有结果比较正常，因为car的样本数很少，学习可能较慢，但是后面应该会会快出现并有较好准确率。

祝好，
献平
________________________________

**Comment by longzhe-csgo** [comment]
感谢你的耐心  我在后边的epoch看到了结果
祝科研顺利！
