### ISSUE TITLE
FTransUNet：代码复现问题

### ISSUE THREAD

**Issue by ttxm-h** [sstary/SSRS#75]
![f8e2c1b8afd9dfdb5512035f262e543b](https://github.com/user-attachments/assets/7a8d5786-c9e4-47fc-8e21-828a7512a1de)
你好，请问复现代码时，一直出现这个问题是什么原因？

**Comment by sstary** [comment]
这是windows系统加载预训练模型的问题，请参考：https://blog.csdn.net/weixin_44091136/article/details/130713925。

**Comment by sstary** [comment]
有帮助请点个star！

**Comment by ttxm-h** [comment]
好嘞，谢谢大佬

**Comment by sstary** [comment]
ATTENTION_Q = "MultiHeadDotProductAttention_1/query"
ATTENTION_K = "MultiHeadDotProductAttention_1/key"
ATTENTION_V = "MultiHeadDotProductAttention_1/value"
ATTENTION_OUT = "MultiHeadDotProductAttention_1/out"

改成

ATTENTION_Q = "MultiHeadDotProductAttention_1\query"
ATTENTION_K = "MultiHeadDotProductAttention_1\key"
ATTENTION_V = "MultiHeadDotProductAttention_1\value"
ATTENTION_OUT = "MultiHeadDotProductAttention_\/out"

试试，如果有其他报错就继续改对应的斜杠。

**Comment by ttxm-h** [comment]
大佬，改了这个，不太行

**Comment by ttxm-h** [comment]
![53133a8cf26e8f6ddbf312baaea49a88](https://github.com/user-attachments/assets/ed81ca33-b120-4b9d-9c85-803f8b2ba567)

**Comment by ttxm-h** [comment]
![image](https://github.com/user-attachments/assets/37ca189c-dc4f-4ef1-bd4d-f59fcc938351)

**Comment by sstary** [comment]
我吃饭，你在issue里搜一下，之前有人也是这个问题。

**Comment by ttxm-h** [comment]
好的，谢谢大佬

**Comment by sstary** [comment]
请参考：https://github.com/jeonsworld/ViT-pytorch/issues/11

**Comment by ttxm-h** [comment]
大佬，我按照链接操作了一遍。还是不行
![image](https://github.com/user-attachments/assets/f29a4aad-b2f8-403b-896c-8a0a4bb47458)
![image](https://github.com/user-attachments/assets/9733c16b-23d4-420e-a51b-5e37cd62067e)

**Comment by sstary** [comment]
ATTENTION_Q = "MultiHeadDotProductAttention_1/query"
ATTENTION_K = "MultiHeadDotProductAttention_1/key"
ATTENTION_V = "MultiHeadDotProductAttention_1/value"
ATTENTION_OUT = "MultiHeadDotProductAttention_1/out"
这个改回去试试。

**Comment by sstary** [comment]
[ROOT + "/" + ATTENTION_Q + "/" + "kernel"]
你多了一组括号？

**Comment by ttxm-h** [comment]
![image](https://github.com/user-attachments/assets/a48d837b-25b2-4a9d-9618-9da44b513f0b)
![image](https://github.com/user-attachments/assets/155c4960-fdb7-4c5d-9074-1a3a8ef65c62)
大佬，又变成这个报错了

**Comment by ttxm-h** [comment]
![image](https://github.com/user-attachments/assets/f7f9695e-ea29-4428-ba40-d4f6ae9fd9f9)
我把反斜杠换了一下，报错没什么变化

**Comment by sstary** [comment]
[ROOT + "/" + ATTENTION_Q + "/" + "kernel"]
你仔细对比下这个和你的代码有没有区别？
如果是这个逗号的问题，那我得夸你一句“眼神儿真好”

**Comment by ttxm-h** [comment]
啊啊，不好意思，我把逗号改了，但是报错还在
![image](https://github.com/user-attachments/assets/3f017727-b4c7-422a-82da-9845abbf1800)
![image](https://github.com/user-attachments/assets/960b9636-b3eb-4769-8424-2e28f8f6bb13)

**Comment by sstary** [comment]
ATTENTION_OUT = "MultiHeadDotProductAttention_1/out"
谨慎啊少年

**Comment by ttxm-h** [comment]
我要晕了

**Comment by sstary** [comment]
别晕，先给我点个star：
![image](https://github.com/user-attachments/assets/a7008a6d-29d3-4471-8eb5-d669e81eef9c)

**Comment by ttxm-h** [comment]
好的，
佬还是报错，
![image](https://github.com/user-attachments/assets/c5278fa0-f4e4-4157-841a-ca1159c96cb0)
![image](https://github.com/user-attachments/assets/3bb9a63b-2130-4682-bc24-cd75bd5ec72b)
![image](https://github.com/user-attachments/assets/f7824b2c-545a-409c-a699-928c175d46a5)

**Comment by sstary** [comment]
不是，你没发现你这一句：ATTENTION_OUT = "MultiHeadDotProductAttention_1/out"
里面少了一个“1”吗？

**Comment by ttxm-h** [comment]
啊啊啊，我改了
![image](https://github.com/user-attachments/assets/58292c0d-60a1-418c-8081-8fcb6cda757a)
还是报错呜呜

**Comment by sstary** [comment]
上面四行都会改了，下面四行不会对着改吗？
举一反三啊少年

**Comment by ttxm-h** [comment]
![image](https://github.com/user-attachments/assets/fef62861-39e3-4132-8322-6eb4c9687062)
![image](https://github.com/user-attachments/assets/4958c8d3-9f28-498e-a4fb-38442ab2f0d4)
![image](https://github.com/user-attachments/assets/35b36254-b2a5-47b3-95f9-3583677e0283)
我把这俩部分都改了，还是报错ε=(´ο｀*)))唉

**Comment by sstary** [comment]
我就知道你还要继续卡着。怎么回你我都想好了：
上面八行都会改了，下面十二行不会对着改吗？
举一反三啊少年
但是你没有举一反三，也算是举一反二了。所以我得这样回你：
上面十二行都会改了，最后八行不会对着改吗？
举一反三啊少年

**Comment by sstary** [comment]
1. pjoin相关的都得改，这之后可能还会有路径问题，但是思路还是一致的，pjoin连接的字符都改成“/”直接相加
2. 要学会看报错信息，你最后一次报错在365行。虽然你每次报错都很类似，但是其实后面的都在进步，每次都不一样的问题。
3

**Comment by ttxm-h** [comment]
嗯嗯嗯，多谢大佬，我在试试

**Comment by ttxm-h** [comment]
大佬，再麻烦你一下
![image](https://github.com/user-attachments/assets/eadf5984-f614-475b-bf70-0d6b538c7f47)

**Comment by sstary** [comment]
这个我不好判断，你会调试吗？把断点打到这一行，然后把posemb和posemb_new的尺寸信息拿出来看看，截个图。

**Comment by ttxm-h** [comment]
![image](https://github.com/user-attachments/assets/5f4d3c6f-59cb-4fc5-b355-7e44124a7857)
佬，是这样

**Comment by sstary** [comment]
我分别是：
torch.Size([1, 197, 768])
torch.Size([1, 1024, 768])
你加载的哪个预训练模型啊？我这个仓库的代码下载之后有改动吗？

**Comment by ttxm-h** [comment]
![image](https://github.com/user-attachments/assets/4b29e649-0dcf-49e1-80ac-b362fcc1fd36)
是这个模型
![image](https://github.com/user-attachments/assets/270ceedf-d8e4-4873-a9ad-038a1291f5e5)
我把这个文件的路径全部改了一下
![image](https://github.com/user-attachments/assets/bd1ba78e-2f25-403a-9ee9-24a95f9f53de)

**Comment by ttxm-h** [comment]
![image](https://github.com/user-attachments/assets/600d7b81-770f-451a-8d42-393e1f976bac)
数据集路径改了一下，剩下的没动

**Comment by sstary** [comment]
按理说你的posemb应该是三维的，但是我也不确定你哪一步出了问题，你还是先学一下调试，去把加载的预训练权重和posemb这一步相关的找出来，加载一个三维的才对，就是看下这步啥情况：posemb = np2th(weights["Transformer/posembed_input/pos_embedding"])

**Comment by sstary** [comment]
再不行，你看看有没有linux环境，windows问题有点多，现在linux上熟悉一下。

**Comment by ttxm-h** [comment]
有虚拟机，不知道能不能跑

**Comment by sstary** [comment]
显存太小的话可能不好跑。
你先研究研究调试，然后会更方便的发现问题。

**Comment by ttxm-h** [comment]
![image](https://github.com/user-attachments/assets/13a5ac40-5486-4048-af3c-e9bb15d09cee)
再麻烦你一下，测试机的model在哪里

**Comment by sstary** [comment]
这是指你自己训练好的模型，选出其中最好的一个，把路径放到YOUR MODEL 那里。

**Comment by ttxm-h** [comment]
刚才好像跑断开了，没有保存模型，我再试试，谢谢

**Comment by sstary** [comment]
这个问题解决了？posemb = np2th(weights["Transformer/posembed_input/pos_embedding"])

**Comment by ttxm-h** [comment]
我放弃在windows上面跑了，在服务器上面试了一下，成功了
![03FC9336](https://github.com/user-attachments/assets/a342deab-e8d3-45e8-bb1e-fd3e4a44b1a3)

**Comment by sstary** [comment]
棒！
很多代码都是在linux上更顺利，而window有各种库、环境的问题。如果你显存不够用的话，需要降低batch size，同时也可以提高总epoch次数。

**Comment by ttxm-h** [comment]
谢谢老师(๑•̀ㅂ•́)و✧

**Comment by sstary** [comment]
不客气，不过我还不是老师。
祝顺利。
