### ISSUE TITLE
MFNet：只使用rgb模态

### ISSUE THREAD

**Issue by HeinZingerRyo** [sstary/SSRS#77]
作者您好，我想在个人数据集上运行MFNet，没有dsm模态，因此想只用rgb模态。在论文A Multilevel Multimodal Fusion Transformer for Remote Sensing Semantic Segmentation的Table IV中也有报告单rgb模态的performance。但是您给出的代码里似乎只有rgb+dsm的版本，请问应该怎么修改来支持单个rgb模态？谢谢！

**Comment by sstary** [comment]
你好，FTransUNet不支持单模态版本，具体原因请根据其计算机制思考。MFNet的单模态版本需要修改SAM相关内容：
1. MFNet/UNetFormer_MMSAM.py 中使用538-542部分，deepx, deepy = self.image_encoder(x, y) # 256*16*16 改成 deepx = self.image_encoder(x) # 256*16*16，此时仅使用单模态，且仅向SAM传入单模态。
1. MFNet/MedSAM/models/sam/modeling/image_encoder.py 中请使用Single modality部分
2. LoRA: MFNet/MedSAM/models/ImageEncoder/vit/lora_block.py文件中的注释部分请打开，而对应的多模态部分需要注释掉。
3. Adapter： MFNet/MedSAM/models/ImageEncoder/vit/adapter_fusionblock.py 同理。
即该模型中有单模态的版本，但是需要你自己手动选择一下。如果有遗漏的地方，请根据报错信息修改对应的位置。
