### ISSUE TITLE
RS^3Mamba：训练模型无法保存

### ISSUE THREAD

**Issue by ttxm-h** [sstary/SSRS#80]

**Comment by ttxm-h** [comment]
![image](https://github.com/user-attachments/assets/c17ee22c-9295-4f1f-9d86-ec1577f110a0)
大佬，我运行这个代码，已经设置了每一次迭代都保存一次模型，但是没有保存，代码一直运行

**Comment by sstary** [comment]
你看下MIoU_Best的值是多少，模型性能比这小的不会保存的，这样可以降低空间占用。

**Comment by ttxm-h** [comment]
大佬，这个是不是训练一个epoch结束才会保存
![image](https://github.com/user-attachments/assets/9b5b937f-4ac9-4d5a-b98c-1e0f4d4ad539)

**Comment by sstary** [comment]
你现在的代码写的上每一个batch测一次，你这里MIoU的值是0.0414，应该是比设置的阈值小的，所以没保存。

**Comment by ttxm-h** [comment]
哦，是的，我设置了0.8
![image](https://github.com/user-attachments/assets/b96d1b1d-6390-4a0f-bdc2-4ee49e879fb8)

**Comment by ttxm-h** [comment]
大佬，是不是要等他慢慢训练，然后iou比0.8高，才会保存？

**Comment by ttxm-h** [comment]
我看这miou一直往下降

**Comment by sstary** [comment]
miou你得一个epoch看一次，优化哪有那么快。这个模型MIoU肯定能到0.8以上的。

**Comment by ttxm-h** [comment]
哦哦，谢谢大佬，还有一个问题，就是Hugging Face Hub 无法找到预训练模型文件，然后我把代码改了一下self.backbone = timm.create_model(backbone_name, features_only=True, output_stride=32, pretrained=False)，pretrained=False这个原来是true。会不会对实验有影响

**Comment by sstary** [comment]
有的，为什么找不到预训练模型呢？resnet18那个能找到的呀。
预训练权重对结果影响挺大的 ，我遇到一般能到七八个点的MIoU的差距。

**Comment by ttxm-h** [comment]
![image](https://github.com/user-attachments/assets/7f9f271d-b291-4925-a06f-4a75f6d6463c)
![image](https://github.com/user-attachments/assets/6033d952-6213-4aec-b9fe-3ccce6945e25)

**Comment by ttxm-h** [comment]
会出现这个报错

**Comment by sstary** [comment]
这个报错你百度下，是因为离timm库版本的问题。

**Comment by ttxm-h** [comment]
嗯嗯好

**Comment by ttxm-h** [comment]
我试一下

**Comment by ttxm-h** [comment]
大佬，成功了！！！
![image](https://github.com/user-attachments/assets/95030641-d8eb-47be-ad52-d8fdddec683e)
谢谢大佬
